# add_wave_group krnl_ai_1
# add_wave -into "krnl_ai_1" {{/pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/krnl_ai_1/inst/ap_clk}} {{/pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/krnl_ai_1/inst/ap_rst_n}} {{/pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/krnl_ai_1/inst/ap_start}} {{/pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/krnl_ai_1/inst/ap_done}} {{/pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/krnl_ai_1/inst/ap_ready}} {{/pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/krnl_ai_1/inst/ap_idle}} {{/pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/krnl_ai_1/inst/ap_rst_n_inv}} 
# add_wave -into "krnl_ai_1" {{/pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/krnl_ai_1/conv2d_19_input_V_data_0_V}} {{/pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/krnl_ai_1/layer22_out_V_data_0_V}} {{/pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/krnl_ai_1/layer22_out_V_data_1_V}} {{/pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/krnl_ai_1/layer22_out_V_data_2_V}} {{/pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/krnl_ai_1/layer22_out_V_data_3_V}} {{/pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/krnl_ai_1/s_axi_AXILiteS}} 

# add_wave_group krnl_mm2s_1
# add_wave -into "krnl_mm2s_1" {{/pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/krnl_mm2s_1/inst/ap_clk}} {{/pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/krnl_mm2s_1/inst/ap_rst_n}} {{/pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/krnl_mm2s_1/inst/ap_rst_reg_2}} {{/pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/krnl_mm2s_1/inst/ap_rst_reg_1}} {{/pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/krnl_mm2s_1/inst/ap_rst_n_inv}} {{/pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/krnl_mm2s_1/inst/ap_start}} {{/pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/krnl_mm2s_1/inst/ap_done}} {{/pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/krnl_mm2s_1/inst/ap_continue}} {{/pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/krnl_mm2s_1/inst/ap_done_reg}} {{/pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/krnl_mm2s_1/inst/ap_idle}} {{/pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/krnl_mm2s_1/inst/ap_ready}} 
# add_wave -into "krnl_mm2s_1" {{/pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/krnl_mm2s_1/k2n}} 

# add_wave_group krnl_s2mm_1
# add_wave -into "krnl_s2mm_1" {{/pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/krnl_s2mm_1/inst/ap_clk}} {{/pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/krnl_s2mm_1/inst/ap_rst_n}} {{/pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/krnl_s2mm_1/inst/ap_rst_reg_2}} {{/pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/krnl_s2mm_1/inst/ap_rst_reg_1}} {{/pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/krnl_s2mm_1/inst/ap_rst_n_inv}} {{/pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/krnl_s2mm_1/inst/ap_start}} {{/pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/krnl_s2mm_1/inst/ap_done}} {{/pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/krnl_s2mm_1/inst/ap_continue}} {{/pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/krnl_s2mm_1/inst/ap_done_reg}} {{/pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/krnl_s2mm_1/inst/ap_idle}} {{/pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/krnl_s2mm_1/inst/ap_ready}} 
# add_wave -into "krnl_s2mm_1" {{/pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/krnl_s2mm_1/n2k}} 

# add_wave {{/pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/krnl_ai_1/inst/conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_8_3_4_0_0_8u_config3_U0/layer3_out_din}} 
# add_wave {{/pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/krnl_ai_1/inst/conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_8_3_4_0_0_8u_config3_U0/layer3_out_write}} 

log_wave -r *